use_default_settings: true

general:
  instance_name: "AI Search"

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: "pl"
  formats:
    - html
    - json    # WAŻNE - Open WebUI wymaga formatu JSON

server:
  secret_key: "eynuVcb9lguk2NVPLpvo3vWOXvq7Gz8"
  bind_address: "0.0.0.0"
  port: 8080

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: google
    engine: google
    shortcut: g
    disabled: false

  - name: github
    engine: github
    shortcut: gh
    disabled: false

  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    disabled: false