services:
  adminer:
    image: adminer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.docker.network=traefik
    networks:
      - traefik
      - adminer
networks:
  adminer:
    name: adminer
    driver: bridge