include:
  - traefik/docker-compose.yml
  - adminer/docker-compose.yml
  # - db/docker-compose.yml   # odkomentuj jeśli potrzebujesz bazy ogólnej

networks:
  server:
    name: server
    driver: bridge